openapi: "3.0.2"
info:
  title: car-registration
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /car:
    post:
      description: car-registration
      operationId: carRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memberId:
                  type: integer
                  format: int64
                  example: 1
                carModelId:
                  type: integer
                  format: int64
                  example: 2
                carNumber:
                  type: string
                  example: "서울30가 0000"
                registrationDate:
                  type: string
                  format: date
                  example: "2018-01-02"
      responses:
        '200':
          description: OK
        default:
          description: ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "존재하지 않는 모델입니다."
