openapi: "3.0.2"
info:
  title: signup
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /member:
    post:
      description: member-signup
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "김동영"
                password:
                  type: string
                  example: "ehddud123!"
                email:
                  type: string
                  format: email
                  example: "yeongdonge@gmail.com"
                nickname:
                  type: string
                  example: "개5판분전"
                birth:
                  type: string
                  format: date
                  example: "1998-02-09"
                gender:
                  type: integer
                  format: int32
                  example: 1
                phone:
                  type: string
                  format: phone
                  example: "010-1234-5678"
      responses:
        '200':
          description: OK
        default:
          description: ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "이미 존재하는 이메일입니다."
