openapi: "3.0.2"
info:
  title: driving-join-request
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /driving-join:
    post:
      description: driving-join-request
      operationId: drivingjoinRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                driverId:
                  type: integer
                  format: int64
                  example: 1
                drivingId:
                  type: integer
                  format: int64
                  example: 2
      responses:
        '200':
          description: OK
        default:
          description: ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "신청 마감된 드라이빙입니다."

