openapi: "3.0.2"
info:
  title: driving-join-response
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /driving-join:
    post:
      description: driving-join-response
      operationId: drivingjoinResponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drivingJoinId:
                  type: integer
                  format: int64
                  example: 1
                status:
                  type: string
                  example: "joined"
      responses:
        '200':
          description: OK
        default:
          description: ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "드라이버가 조인 요청을 취소하였습니다."

